@echo off
REM Demo Starter Script for visualize-superset (Windows)
REM This script starts all services needed for a demo without Docker
REM
REM Features:
REM - Checks for required dependencies (Node.js, Python, pip)
REM - Installs Python dependencies for sparql-proxy if needed
REM - Installs npm dependencies for frontend if needed
REM - Starts the SPARQL proxy service in background
REM - Starts the frontend dev server
REM - Opens the browser automatically
REM - Handles cleanup on exit (kill background processes)

setlocal EnableDelayedExpansion

REM Get the project root directory (parent of scripts directory)
set "SCRIPT_DIR=%~dp0"
set "PROJECT_ROOT=%SCRIPT_DIR%.."
cd /d "%PROJECT_ROOT%"
set "PROJECT_ROOT=%CD%"

REM Service ports
set "SPARQL_PROXY_PORT=8089"
set "FRONTEND_PORT=5173"

REM Default LINDAS endpoint
set "LINDAS_ENDPOINT=https://lindas.admin.ch/query"

REM Python command (will be determined)
set "PYTHON_CMD="

REM Process IDs
set "SPARQL_PID="
set "FRONTEND_PID="

echo.
echo ========================================
echo Visualize-Superset Demo Starter
echo Platform: Windows
echo ========================================
echo.

REM ============================================
REM Check Dependencies
REM ============================================
echo [STEP] Checking dependencies...

REM Check Node.js
node --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Node.js not found
    echo Please install Node.js 18+ from https://nodejs.org/
    pause
    exit /b 1
)

for /f "tokens=*" %%a in ('node --version') do set "NODE_VERSION=%%a"
set "NODE_VERSION=!NODE_VERSION:v=!"
echo [SUCCESS] Node.js found: v!NODE_VERSION!

REM Check npm
npm --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] npm not found
    echo Please install Node.js (includes npm) from https://nodejs.org/
    pause
    exit /b 1
)
for /f "tokens=*" %%a in ('npm --version') do set "NPM_VERSION=%%a"
echo [SUCCESS] npm found: v!NPM_VERSION!

REM Check Python
python --version >nul 2>&1
if errorlevel 1 (
    python3 --version >nul 2>&1
    if errorlevel 1 (
        echo [ERROR] Python not found
        echo Please install Python 3.10+ from https://www.python.org/
        pause
        exit /b 1
    ) else (
        set "PYTHON_CMD=python3"
        for /f "tokens=*" %%a in ('python3 --version') do set "PYTHON_VERSION=%%a"
    )
) else (
    set "PYTHON_CMD=python"
    for /f "tokens=*" %%a in ('python --version') do set "PYTHON_VERSION=%%a"
)
echo [SUCCESS] !PYTHON_VERSION! found

REM Check pip
!PYTHON_CMD! -m pip --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] pip not found
    echo Please ensure pip is installed with Python
    pause
    exit /b 1
)
echo [SUCCESS] pip found

echo [SUCCESS] All dependencies satisfied!
echo.

REM ============================================
REM Setup SPARQL Proxy
REM ============================================
echo [STEP] Setting up SPARQL Proxy...

cd /d "%PROJECT_ROOT%\sparql-proxy"

REM Create virtual environment if it doesn't exist
if not exist "venv" (
    echo [INFO] Creating Python virtual environment...
    !PYTHON_CMD! -m venv venv
    if errorlevel 1 (
        echo [ERROR] Failed to create virtual environment
        pause
        exit /b 1
    )
    echo [SUCCESS] Virtual environment created
)

REM Activate virtual environment
echo [INFO] Activating virtual environment...
call venv\Scripts\activate.bat
if errorlevel 1 (
    echo [ERROR] Failed to activate virtual environment
    pause
    exit /b 1
)

REM Install dependencies
echo [INFO] Installing Python dependencies...
pip install -q -r requirements.txt
if errorlevel 1 (
    echo [ERROR] Failed to install Python dependencies
    pause
    exit /b 1
)
echo [SUCCESS] Python dependencies installed

cd /d "%PROJECT_ROOT%"
echo.

REM ============================================
REM Setup Frontend
REM ============================================
echo [STEP] Setting up Frontend...

cd /d "%PROJECT_ROOT%\frontend"

REM Install npm dependencies if needed
if not exist "node_modules" (
    echo [INFO] Installing npm dependencies (this may take a while)...
    call npm install
    if errorlevel 1 (
        echo [ERROR] Failed to install npm dependencies
        pause
        exit /b 1
    )
    echo [SUCCESS] npm dependencies installed
) else (
    echo [INFO] npm dependencies already installed
)

REM Create .env file if it doesn't exist
if not exist ".env" (
    echo [INFO] Creating .env file...
    (
        echo # SPARQL Proxy Configuration (auto-generated by demo-start.bat)
        echo VITE_SPARQL_PROXY_URL=http://localhost:%SPARQL_PROXY_PORT%
    ) > .env
    echo [SUCCESS] .env file created
) else (
    echo [INFO] .env file already exists
)

cd /d "%PROJECT_ROOT%"
echo.

REM ============================================
REM Kill existing processes on ports
REM ============================================
echo [STEP] Checking for existing processes...

REM Kill process on port 8089 (SPARQL Proxy)
for /f "tokens=5" %%a in ('netstat -aon ^| findstr ":%SPARQL_PROXY_PORT%"') do (
    echo [INFO] Killing existing process on port %SPARQL_PROXY_PORT% (PID: %%a)...
    taskkill /F /PID %%a >nul 2>&1
)

REM Kill process on port 5173 (Frontend)
for /f "tokens=5" %%a in ('netstat -aon ^| findstr ":%FRONTEND_PORT%"') do (
    echo [INFO] Killing existing process on port %FRONTEND_PORT% (PID: %%a)...
    taskkill /F /PID %%a >nul 2>&1
)

timeout /t 2 /nobreak >nul
echo.

REM ============================================
REM Start SPARQL Proxy
REM ============================================
echo [STEP] Starting SPARQL Proxy...

cd /d "%PROJECT_ROOT%\sparql-proxy"
call venv\Scripts\activate.bat

REM Set environment variables
set "LINDAS_ENDPOINT_URL=%LINDAS_ENDPOINT%"
set "LOG_LEVEL=INFO"

echo [INFO] Starting SPARQL Proxy on port %SPARQL_PROXY_PORT%...

REM Start Python in background using start command
start "SPARQL Proxy" /MIN cmd /c "python -m uvicorn src.main:app --host 0.0.0.0 --port %SPARQL_PROXY_PORT% ^> "%PROJECT_ROOT%\sparql-proxy.log" 2^>^&1"

REM Get the PID of the started process (approximate)
for /f "tokens=2" %%a in ('tasklist ^| findstr "python"') do (
    set "SPARQL_PID=%%a"
)

cd /d "%PROJECT_ROOT%"

echo [SUCCESS] SPARQL Proxy started
echo [INFO] Waiting for SPARQL Proxy to be ready...

REM Wait for service to be ready
set /a retries=0
:wait_sparql
ping -n 2 127.0.0.1 >nul
curl -s "http://localhost:%SPARQL_PROXY_PORT%/api/v1/health" >nul 2>&1
if errorlevel 1 (
    set /a retries+=1
    if !retries! lss 30 (
        echo|set /p="."
        goto wait_sparql
    ) else (
        echo.
        echo [WARNING] SPARQL Proxy may not be fully ready yet, continuing anyway...
    )
) else (
    echo.
    echo [SUCCESS] SPARQL Proxy is ready!
)
echo.

REM ============================================
REM Start Frontend
REM ============================================
echo [STEP] Starting Frontend...

cd /d "%PROJECT_ROOT%\frontend"

echo [INFO] Starting Frontend dev server on port %FRONTEND_PORT%...

REM Start npm in background using start command
start "Frontend Dev Server" /MIN cmd /c "npm run dev ^> "%PROJECT_ROOT%\frontend.log" 2^>^&1"

REM Get the PID of the started process (approximate)
for /f "tokens=2" %%a in ('tasklist ^| findstr "node"') do (
    set "FRONTEND_PID=%%a"
)

cd /d "%PROJECT_ROOT%"

echo [SUCCESS] Frontend started
echo [INFO] Waiting for Frontend to be ready...

REM Wait for service to be ready
set /a retries=0
:wait_frontend
ping -n 2 127.0.0.1 >nul
curl -s "http://localhost:%FRONTEND_PORT%" >nul 2>&1
if errorlevel 1 (
    set /a retries+=1
    if !retries! lss 30 (
        echo|set /p="."
        goto wait_frontend
    ) else (
        echo.
        echo [WARNING] Frontend may not be fully ready yet, continuing anyway...
    )
) else (
    echo.
    echo [SUCCESS] Frontend is ready!
)
echo.

REM ============================================
REM Open Browser
REM ============================================
echo [STEP] Opening browser...
ping -n 3 127.0.0.1 >nul
start http://localhost:%FRONTEND_PORT%
echo [SUCCESS] Browser opened (or attempted to open)
echo.

REM ============================================
REM Print Status
REM ============================================
echo ========================================
echo  Demo Environment Ready!
echo ========================================
echo.
echo Services:
echo   - Frontend:     http://localhost:%FRONTEND_PORT%
echo   - SPARQL Proxy: http://localhost:%SPARQL_PROXY_PORT%
echo   - LINDAS:       %LINDAS_ENDPOINT%
echo.
echo API Endpoints:
echo   - Health:    http://localhost:%SPARQL_PROXY_PORT%/api/v1/health
echo   - Cubes:     http://localhost:%SPARQL_PROXY_PORT%/api/v1/cubes
echo   - GraphQL:   http://localhost:%SPARQL_PROXY_PORT%/graphql
echo.
echo Logs:
echo   - SPARQL Proxy: %PROJECT_ROOT%\sparql-proxy.log
echo   - Frontend:     %PROJECT_ROOT%\frontend.log
echo.
echo Commands:
echo   - Stop services: Close this window or press Ctrl+C
echo   - View SPARQL Proxy: See window titled "SPARQL Proxy"
echo   - View Frontend:     See window titled "Frontend Dev Server"
echo ========================================
echo.

REM ============================================
REM Keep script running
REM ============================================
echo [INFO] Services are running. Close this window to stop all services.
echo.

REM Create a stop script
echo @echo off > "%PROJECT_ROOT%\stop-demo.bat"
echo echo Stopping demo services... >> "%PROJECT_ROOT%\stop-demo.bat"
echo taskkill /F /FI "WINDOWTITLE eq SPARQL Proxy" 2^>nul >> "%PROJECT_ROOT%\stop-demo.bat"
echo taskkill /F /FI "WINDOWTITLE eq Frontend Dev Server" 2^>nul >> "%PROJECT_ROOT%\stop-demo.bat"
echo for /f "tokens=5" %%%%a in ('netstat -aon ^| findstr ":8089"') do taskkill /F /PID %%%%a 2^>nul >> "%PROJECT_ROOT%\stop-demo.bat"
echo for /f "tokens=5" %%%%a in ('netstat -aon ^| findstr ":5173"') do taskkill /F /PID %%%%a 2^>nul >> "%PROJECT_ROOT%\stop-demo.bat"
echo echo Services stopped. >> "%PROJECT_ROOT%\stop-demo.bat"

:loop
ping -n 10 127.0.0.1 >nul

REM Check if services are still running
curl -s "http://localhost:%SPARQL_PROXY_PORT%/api/v1/health" >nul 2>&1
if errorlevel 1 (
    curl -s "http://localhost:%FRONTEND_PORT%" >nul 2>&1
    if errorlevel 1 (
        echo [WARNING] Services appear to have stopped. Exiting...
        goto cleanup
    )
)

goto loop

:cleanup
echo.
echo [INFO] Cleaning up...
call "%PROJECT_ROOT%\stop-demo.bat" 2>nul
echo [INFO] Cleanup complete!
echo.
echo Thank you for using visualize-superset!
pause
